### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by bennyn** [wireapp/wire-webapp-cbor#4]
Like:

- https://github.com/wireapp/proteus.js/blob/v5.0.0/dist/typings/proteus.d.ts#L1

```typescript
export module CBOR {
  class Encoder {
    encode(value: any): any;
  }

  class Decoder {
    decode(value: any): any;
  }
}
```

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/wire-webapp-cbor/compare/450da83f16ed4e0e231a08474e1f75e65b01bb5a...944955422ef79f92fd2652ec9a4f1685b6de3e78.
